
package Principal;

import conexion.conexionMysql;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class frmregistro extends javax.swing.JDialog {
    conexion.conexionMysql con=new conexionMysql();
    Connection cn=con.conectar();
    public frmregistro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtnombre = new javax.swing.JTextField();
        txtapellidos = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        txtusuario = new javax.swing.JTextField();
        txtcontraseña = new javax.swing.JPasswordField();
        txtconfirmar = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de Nuevos Usuarios");

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        jPanel2.setBackground(new java.awt.Color(51, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Registro de Usuario")));

        txtnombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));

        txtapellidos.setBorder(javax.swing.BorderFactory.createTitledBorder("Apellidos"));

        txtemail.setBorder(javax.swing.BorderFactory.createTitledBorder("Email"));

        txttelefono.setBackground(new java.awt.Color(240, 240, 240));
        txttelefono.setBorder(javax.swing.BorderFactory.createTitledBorder("Telefono"));
        txttelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelefonoKeyTyped(evt);
            }
        });

        txtusuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuario"));

        txtcontraseña.setBorder(javax.swing.BorderFactory.createTitledBorder("Contraseña"));

        txtconfirmar.setBorder(javax.swing.BorderFactory.createTitledBorder("Confirmar contraseña"));
        txtconfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtconfirmarActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("REGISTRAR USUARIO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtconfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                    .addComponent(txtcontraseña)
                    .addComponent(txtusuario)
                    .addComponent(txtemail)
                    .addComponent(txtapellidos)
                    .addComponent(txtnombre)
                    .addComponent(txttelefono)))
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtconfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        txtconfirmar.getAccessibleContext().setAccessibleName("Confirma contraseña");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(229, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        int id=0;
        String Usuario=txtusuario.getText();
        String Nombre=txtnombre.getText();
        String Apellidos=txtapellidos.getText();
        String Email=txtemail.getText();
        String Telefono=txttelefono.getText();
        String Contraseña=txtcontraseña.getText();
        String Confirmar=txtconfirmar.getText();
        int Nivel = 0;
        List Camposincompletos = new ArrayList();
        
       boolean Cuser = Usuario.isEmpty()? false: true;
       boolean Cnombre = Nombre.isEmpty()? false: true;
       boolean CApeliido = Apellidos.isEmpty()? false: true;
       boolean Cemail = Email.isEmpty()? false: true;
       boolean CTelefono = Telefono.isEmpty()? false: true;  
       boolean Ccontrasena = Contraseña.isEmpty()? false: true;
       boolean CConfirmar = Confirmar.isEmpty()? false: true;
       
       if(Cuser == false){Camposincompletos.add("Usuario" + "\n");};
       if(Cnombre == false){Camposincompletos.add("Nombre" +  "\n");};
       if(CApeliido == false){Camposincompletos.add("Apellido" + "\n");};
       if(Cemail == false){Camposincompletos.add("Email" + "\n");};
       if(CTelefono == false){Camposincompletos.add("Telefono" + "\n");};
       if(Ccontrasena == false){Camposincompletos.add("Contraseña" + "\n");};
       if(CConfirmar == false){Camposincompletos.add("Confirmar contraseña" + "\n");};
       
       
           String Cincompleto="";
          //int Tel = Integer.parseInt(txttelefono.getText());
      
       
        
           
            
             if(Camposincompletos.size()>0){
           
         for(int i=0;i<Camposincompletos.size();i++){
           
           
       Cincompleto+=Camposincompletos.get(i);
       
       }
         JOptionPane.showMessageDialog(null,("Debes de completar el/los siguientes campos: " + "\n" + Cincompleto ));
         
       
       }else if(!Contraseña.equals(Confirmar)){
       JOptionPane.showMessageDialog(null,"La contraseña no coincide.");
       }
        else{
              //Comprobando que el usuario o el correo no esté registrado   
            try {
                
                PreparedStatement Comprobar_usuario_existente=cn.prepareStatement("SELECT * FROM usuarios WHERE Usuario='"+Usuario+"'");
                PreparedStatement Comprobar_correo_existente=cn.prepareStatement("SELECT * FROM usuarios WHERE Email='"+Email+"'");
                ResultSet ComUsu = Comprobar_usuario_existente.executeQuery();
                ResultSet CCorreo = Comprobar_correo_existente.executeQuery();
                ComUsu.next();
                CCorreo.next();
                if(ComUsu.getRow()> 0 || CCorreo.getRow()> 0){
                
                    if(ComUsu.getRow()> 0){JOptionPane.showMessageDialog(null,"Usuario ya existe.");}
                    if(CCorreo.getRow()> 0){JOptionPane.showMessageDialog(null,"Correo ya existe.");}
                    
  
                
                }else{
                
                
                    
                    try {
                    String consulta="INSERT INTO usuarios (id,Nombre,Apellidos,Usuario,Email,Contraseña,Confirmar,Telefono,Nivel) VALUES('"+id+"','"+Nombre+"','"+Apellidos+"','"+Usuario+"','"+Email+"','"+Contraseña+"','"+Confirmar+"','"+Telefono+"','"+Nivel+"')";
                    PreparedStatement ps=cn.prepareStatement(consulta);
                    ps.executeUpdate();
                    limpiar();
                    JOptionPane.showMessageDialog(null,"Datos Guardados Correctamente");
                }catch (Exception e){
                    JOptionPane.showConfirmDialog(null, "No se pudo guardar Usuario"+ e);
                }
                    
                    
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(frmregistro.class.getName()).log(Level.SEVERE, null, ex);
            }

          
                        
//----------------
                
           
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtconfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtconfirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconfirmarActionPerformed

    private void txttelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefonoKeyTyped
        // TODO add your handling code here:
        
         int key = evt.getKeyChar();

    boolean numeros = key >= 48 && key <= 57;
    
     if (!numeros)
    {
        evt.consume();
    }

    if (txttelefono.getText().trim().length() == 10) {
        evt.consume();
    }
        
        
    }//GEN-LAST:event_txttelefonoKeyTyped
        void limpiar (){
            txtusuario.setText("");
            txtnombre.setText("");
            txtapellidos.setText("");
            txtemail.setText("");
            txttelefono.setText("");
            txtcontraseña.setText("");
            txtconfirmar.setText("");
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmregistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmregistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmregistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmregistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmregistro dialog = new frmregistro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtapellidos;
    private javax.swing.JPasswordField txtconfirmar;
    private javax.swing.JPasswordField txtcontraseña;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttelefono;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
