/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package Formulario;

import Principal.frmlogin;
import conexion.conexionMysql;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ander
 */
public class panel_usuario_Administrador extends javax.swing.JFrame {
conexionMysql con=new conexionMysql();
    Connection cn=con.conectar();
    
    DefaultTableModel dtm;
    Object[] Obj = new Object[6];
    
      public void Mostrardatos(){
          dtm =  (DefaultTableModel) Tabla.getModel();
          dtm.setRowCount(0);
        String qry1 = "SELECT * FROM usuarios";
        try {
        
        PreparedStatement datos=cn.prepareStatement(qry1);
        ResultSet rs = datos.executeQuery();
        
       while(rs.next()){

 Obj[0]=rs.getString("Usuario");
 Obj[1]=rs.getString("Nombre");
 Obj[2]=rs.getString("Apellidos");
 Obj[3]=rs.getString("Telefono");
 Obj[4]=rs.getString("Email");
 Obj[5]=rs.getString("Contraseña");
 dtm.addRow(Obj);
 
    }
    

       
       
        
       
        
        }catch(Exception e){
            
        System.out.println(e);
               }
    }
        
    /** Creates new form panel_usuario_Administrador */
    public panel_usuario_Administrador() {
        initComponents();
        dtm = (DefaultTableModel) Tabla.getModel();
        Mostrardatos();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cerrarsesion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        UsuarioF = new javax.swing.JTextField();
        NombreF = new javax.swing.JTextField();
        ApellidoF = new javax.swing.JTextField();
        ContraseñaF = new javax.swing.JTextField();
        EmailF = new javax.swing.JTextField();
        TelF1 = new javax.swing.JTextField();
        Extraerinfo = new javax.swing.JButton();
        EliminarUSUARIO = new javax.swing.JButton();
        Editaruser = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 204, 255));
        setBounds(new java.awt.Rectangle(10, 10, 10, 10));

        Cerrarsesion.setText("Cerrar sesión");
        Cerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarsesionActionPerformed(evt);
            }
        });

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuario", "Nombre", "Apellido", "Teléfono", "Email", "Contraseña"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla);

        jButton1.setText("Actualizar informacion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        UsuarioF.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Usuario"))));
        UsuarioF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioFActionPerformed(evt);
            }
        });

        NombreF.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));
        NombreF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreFActionPerformed(evt);
            }
        });

        ApellidoF.setBorder(javax.swing.BorderFactory.createTitledBorder("Apellido"));
        ApellidoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidoFActionPerformed(evt);
            }
        });

        ContraseñaF.setBorder(javax.swing.BorderFactory.createTitledBorder("Contraseña"));
        ContraseñaF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaFActionPerformed(evt);
            }
        });

        EmailF.setBorder(javax.swing.BorderFactory.createTitledBorder("Email"));
        EmailF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailFActionPerformed(evt);
            }
        });

        TelF1.setBorder(javax.swing.BorderFactory.createTitledBorder("Teléfono\n"));
        TelF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelF1ActionPerformed(evt);
            }
        });
        TelF1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TelF1KeyTyped(evt);
            }
        });

        Extraerinfo.setText("Buscar");
        Extraerinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExtraerinfoActionPerformed(evt);
            }
        });

        EliminarUSUARIO.setText("Eliminar usuario");
        EliminarUSUARIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarUSUARIOActionPerformed(evt);
            }
        });

        Editaruser.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuario"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Cerrarsesion, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ApellidoF, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NombreF, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(ContraseñaF, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addComponent(Editaruser, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(EmailF, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TelF1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(UsuarioF, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(Extraerinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(EliminarUSUARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Cerrarsesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UsuarioF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Extraerinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EliminarUSUARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmailF)
                            .addComponent(TelF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NombreF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ApellidoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ContraseñaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(Editaruser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarsesionActionPerformed
        // TODO add your handling code here:
        
     this.setVisible(false);
     new frmlogin(null,true).setVisible(true);
    
    }//GEN-LAST:event_CerrarsesionActionPerformed

    private void UsuarioFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioFActionPerformed

    private void NombreFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreFActionPerformed

    private void ApellidoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidoFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidoFActionPerformed

    private void ContraseñaFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaFActionPerformed

    private void EmailFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        List Camposincompletos = new ArrayList();
        
        String Usuario=UsuarioF.getText();
        String Nombre=NombreF.getText();
        String Apellidos=ApellidoF.getText();
        String Email=EmailF.getText();
        String Telefono=TelF1.getText();
        String Contraseña=ContraseñaF.getText();
        String Editarusuario=Editaruser.getText();
        
        
       
       boolean Cuser = Usuario.isEmpty()? false: true;
       boolean Cnombre = Nombre.isEmpty()? false: true;
       boolean CApeliido = Apellidos.isEmpty()? false: true;
       boolean Cemail = Email.isEmpty()? false: true;
       boolean CTelefono = Telefono.isEmpty()? false: true;
       boolean Ccontrasena = Contraseña.isEmpty()? false: true;
       boolean CEditarusuario = Editarusuario.isEmpty()? false: true;
       
       String Cincompleto="";
       
       //if(Cuser == false){Camposincompletos.add("Usuario" + "\n");};
       if(Cnombre == false){Camposincompletos.add("Nombre" +  "\n");};
       if(CApeliido == false){Camposincompletos.add("Apellido" + "\n");};
       if(Cemail == false){Camposincompletos.add("Email" + "\n");};
       if(CTelefono == false){Camposincompletos.add("Telefono" + "\n");};
       if(Ccontrasena == false){Camposincompletos.add("Contraseña" + "\n");};
       if(CEditarusuario == false){Camposincompletos.add("Usuario" + "\n");};
       
                    if(Camposincompletos.size()>0){
           
         for(int i=0;i<Camposincompletos.size();i++){
           
           
       Cincompleto+=Camposincompletos.get(i);
       
       }
         JOptionPane.showMessageDialog(null,("Favor completar: " + "\n" + Cincompleto ));
         
       
       }else{
                        
                 try{
                     
 String Qry= "UPDATE usuarios SET Nombre = ? ,Apellidos = ? , Usuario =  ? , Email = ? , Contraseña = ? , Confirmar =  ?, Telefono = ? WHERE usuario = ?";
   PreparedStatement Upd=cn.prepareStatement(Qry);  
   Upd.setString(1, Nombre);
   Upd.setString(2, Apellidos);
   Upd.setString(3, Editarusuario);
   Upd.setString(4, Email);
   Upd.setString(5, Contraseña);
   Upd.setString(6, Contraseña);
   Upd.setString(7, Telefono);
   Upd.setString(8, Usuario);
   Upd.executeUpdate();
   
        NombreF.setText("");
        ApellidoF.setText("");
        EmailF.setText("");
        ContraseñaF.setText("");
        TelF1.setText("");
        Editaruser.setText("");
        UsuarioF.setText("");
        

   Mostrardatos();
   
   JOptionPane.showMessageDialog(null,"Los datos fueros actualizados");
   

                 }catch(Exception e){
                 System.out.println(e);
                 } 
                    
                    }
           
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TelF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelF1ActionPerformed

    private void ExtraerinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExtraerinfoActionPerformed
        // TODO add your handling code here:
        
    
    String Usuario=UsuarioF.getText();
    if(true == Usuario.isEmpty()){
        JOptionPane.showMessageDialog(null,"Campo no puede estar vacio");
    }else{
    
    
        
        
    try {
        
               PreparedStatement info=cn.prepareStatement("SELECT * FROM usuarios WHERE Usuario='"+Usuario+"'");
               ResultSet Uinfo=info.executeQuery();
               Uinfo.next();
               System.out.println(Uinfo.getRow());
               if(Uinfo.getRow()>0){
                   
        NombreF.setText(Uinfo.getString("Nombre"));
        ApellidoF.setText(Uinfo.getString("Apellidos"));
        EmailF.setText(Uinfo.getString("Email"));
        ContraseñaF.setText(Uinfo.getString("Contraseña"));
        TelF1.setText(Uinfo.getString("Telefono"));
        Editaruser.setText(Uinfo.getString("Usuario"));
        
        
               }else{
               
               JOptionPane.showMessageDialog(null,"Usuario no encontrado.");
               }
               
               
    }catch(Exception e){
    }
    }
    
    
    
        
        
        
    }//GEN-LAST:event_ExtraerinfoActionPerformed

    private void EliminarUSUARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarUSUARIOActionPerformed
        // TODO add your handling code here:
        String Usuario=UsuarioF.getText();
        String qry = "DELETE FROM usuarios WHERE Usuario = ? ";
        String qry1 = "SELECT * FROM usuarios WHERE Usuario = ? ";
    if(true == Usuario.isEmpty()){
        JOptionPane.showMessageDialog(null,"Campo no puede estar vacio");
    }else{
        
        try {
        
        PreparedStatement Cuser=cn.prepareStatement(qry1);
        Cuser.setString(1,UsuarioF.getText());
        ResultSet rs = Cuser.executeQuery();
        rs.next();
        
        if(rs.getRow()>0){
            
        PreparedStatement Eliusu=cn.prepareStatement(qry);
        Eliusu.setString(1,UsuarioF.getText());
        Eliusu.executeUpdate();
        JOptionPane.showMessageDialog(null,"Usuario eliminado.");
        Mostrardatos();
        
        
            }else{
                    JOptionPane.showMessageDialog(null,"Usuario no encontrado.");}
        
    } catch (SQLException ex) {
        System.out.println(ex);
    }}

        
    }//GEN-LAST:event_EliminarUSUARIOActionPerformed

    private void TelF1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelF1KeyTyped
        // TODO add your handling code here:
    int key = evt.getKeyChar();

    boolean numeros = key >= 48 && key <= 57;
    
     if (!numeros)
    {
        evt.consume();
    }

    if (TelF1.getText().trim().length() == 10) {
        evt.consume();
    }
        
        
        
    }//GEN-LAST:event_TelF1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panel_usuario_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panel_usuario_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panel_usuario_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panel_usuario_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panel_usuario_Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoF;
    private javax.swing.JButton Cerrarsesion;
    private javax.swing.JTextField ContraseñaF;
    private javax.swing.JTextField Editaruser;
    private javax.swing.JButton EliminarUSUARIO;
    private javax.swing.JTextField EmailF;
    private javax.swing.JButton Extraerinfo;
    private javax.swing.JTextField NombreF;
    private javax.swing.JTable Tabla;
    private javax.swing.JTextField TelF1;
    private javax.swing.JTextField UsuarioF;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
